import Header from "@/components/Header";
import Providers from "@/components/providers";
import '../styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className="overflow-x-hidden">
          <Header />
          {children}
        </body>
      </Providers>
    </html>
  );
}
